name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install webkit2gtk
      run: sudo apt-get install libwebkit2gtk-4.0-37
    - name: Build
      run: cargo build --verbose
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
      with:
        # GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        toolchain: nightly
