name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install webkit2gtk
      run: sudo apt-get install libwebkit2gtk-4.0-dev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Cargo Build
      uses: actions-rs/cargo@v1.0.1
      with:
        # Cargo command to run (ex. `check` or `build`)
        command: build
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        toolchain: nightly
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        # GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        toolchain: nightly
